const DataBlog = [
    {
        id: 1,
        title: 'Mengenal Front End dan Back End Developer: Skill yang Dibutuhkan, Hingga Perbedaannya',
        descript: 'Sederhanya front end developer adalah pekerjaan dalam bentuk pemrograman yang mengelola dan mengembangkan tampilan sebuah aplikasi atau website. Adapun hal yang biasa dilakukan oleh front end developer yaitu mengkombinasikan teknik desain, teknologi, dan pemrograman untuk menghasilkan tampilan situs web yang menarik, interaktif, serta menangani debugging (masalah) yang terjadi. Dalam aktivitasnya, front end developer akan sering bekerja menggunakan HTML, CSS, dan JavaScript untuk mengembangkan situs web atau aplikasi web. Sehingga pengguna dapat melihat dan berinteraksi dengan produk tersebut secara langsung. Jika front end lebih banyak berurusan dengan tampilan situs web dan berorientasi dengan kenyamanan pengunjung, maka back end developer lebih banyak bekerja dengan hal-hal yang terkait server dari sebuah aplikasi atau situs web. Dikutip dari indeed.com, back end developer adalah pekerjaan yang bertugas mengembankan, menyimpan data, dan komunikasi antara database situs web atau aplikasi. Tiga komponen utama dari pekerjaan back end developer yaitu server, aplikasi, dan database. Sehingga back end developer juga memiliki peran penting dalam kinerja situs web atau aplikasi. Pada praktiknya, front end developer menggunakan berbagai jenis alat, bahasa pemrograman, dan kerangka kerja untuk menyelesaikan pekerjaannya. Untuk melakukan hal tersebut, mereka menggunakan berbagai jenis program mulai dari Java, .NET, PHP, Ruby, NodeJS, dan Python. ',
        img: "https://www.monitorteknologi.com/wp-content/uploads/2020/07/Perbedaan-Front-End-Dan-Back-End-Developer.jpg",
    },
    {
        id: 2,
        title: 'Cara Menjadi Web Developer Untuk Pemula',
        descript: 'Dalam beberapa tahun terakhir, web development menjadi salah satu skill yang paling banyak dicari di industri saar ini. Pernahkah terlintas di pikiranmu, bagaimana cara menjadi seorang Web Developer? Sebenarnya, kamu tidak perlu gelar sarjana dalam ilmu komputer untuk menjadi developer. Hanya saja, kamu harus bisa konsisten dan persisten karena belajar coding lebih dari sekadar menyusun kode dengan bahasa pemrograman. Jika kamu tertarik menjadi seorang Web Developer, mari kita mulai dengan dasar-dasarnya. Secara sederhana, seorang Web Developer adalah orang yang membangun dan memelihara sebuah website. Dengan kata lain, mereka lah yang menentukan pengalaman user dalam menggunakan sebuah website. Untuk itu, seorang developer harus bisa membuat website yang menarik dan interaktif. Tidak jarang perusahaan rela membayar mahal Web Developer yang memiliki kemampuan tersebut. Berikut beberapa pekerjaan Web Developer yang harus kamu ketahui. Menulis halaman web dengan kombinasi bahasa markup, Membuat mockup dan prototipe berkualitas, Membangun situs WordPress dari awal, Memahami HTML dan CMS, Memahami UI/UX, Mengembangkan website dan aplikasi berbasis web yang fungsional dan menarik, Menyediakan pemeliharaan dan peningkatan website, Ini adalah persyaratan yang paling umum, tetapi tanggung jawab dan tugas seorang Web Developer akan bervariasi tergantung pada pertunjukan web development serta spesialisasi mereka. Adapun tiga spesialisasi web development yang harus kamu ketahui, sebagai berikut.Front-End Development: "Front-End" mengacu pada "barang" di website yang kamu lihat dan berinteraksi dengannya. Contoh: tombol menu, dropdown, dll. Back-End Development: “Back-End” seperti bagian gunung es di bawah permukaan. Tanpa itu, website tidak dapat berfungsi. Backend berhubungan dengan server, aplikasi, database, dll. Full Stack Development: Ini adalah kombinasi dari developer Back-End dan Front-End.',
        img: "https://berkarir.id/wp-content/uploads/2020/07/web-developer-multitasking.jpg",
    },
    {
        id: 3,
        title: 'tugas product manager',
        descript: 'Secara sederhana, product manager bertanggung jawab pada bagian perencanaan dan pengembangan produk tertentu. Dalam perencanaan produk, seorang product manager harus merancang produk baru yang memiliki daya tarik tinggi setelah menganalisis data penjualan masa lampau, tren, kekhasan produk yang serupa, dan permintaan konsumen. Untuk itu, pekerjaan ini membutuhkan ide revolusioner yang belum pernah ada dan usaha keras yang untuk menciptakan sesuatu yang orisinil, Quipperian. Terdapat tim besar yang terlibat dengan pekerjaan ini yang bertanggung jawab pada banyak hal, mulai dari penyusunan ide sampai dalam hal menentukan harga, hingga membuat strategi penjualan. Yup, product manager bertanggung jawab membawahi tim untuk keseluruhan strategi, mulai dari mengidentifikasi produk potensial, melakukan riset pasar, menentukan spesifikasi, menentukan jadwal produksi dan harga, hingga mengembangkan strategi pemasaran.',
        img: "https://assets.website-files.com/61af164800e38cf1b6c60b55/62e3d53cdfcba7396415c28b_L1EW3L2S_IWjqsY6g_XkFWAnRXGhjz_-362RCCWWum3sUuoqwSfz3qWptIsUuVnNIu3kHhD_ylrboLe9GnSO5xdS-rFdBY43rVfHTJ6pO2T9Jk0iFfHzQnUAyNWx84An0US1mVdxwG6_U8YEmuSVj38.png",
    },
];

export default DataBlog;